// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exec(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function List(arg1:string):Promise<string>;

export function ProjectDelete(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ProjectForm(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ProjectInfo(arg1:string,arg2:string):Promise<string>;

export function ServerAdd(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function ServerDelete(arg1:string,arg2:string):Promise<string>;

export function ServerInfo(arg1:string,arg2:string):Promise<string>;

export function ServerUpdate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function TestSSHConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function TestStoredServerSSH(arg1:string,arg2:string):Promise<string>;

export function TestUnauthorized():Promise<string>;
