// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exec(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Exec'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function List(arg1) {
  return window['go']['main']['App']['List'](arg1);
}

export function ProjectDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProjectDelete'](arg1, arg2, arg3);
}

export function ProjectForm(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProjectForm'](arg1, arg2, arg3);
}

export function ProjectInfo(arg1, arg2) {
  return window['go']['main']['App']['ProjectInfo'](arg1, arg2);
}

export function ServerInfo(arg1, arg2) {
  return window['go']['main']['App']['ServerInfo'](arg1, arg2);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function TestUnauthorized() {
  return window['go']['main']['App']['TestUnauthorized']();
}
