// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CapturePage(arg1:string,arg2:string):Promise<string>;

export function CloudflareBatchConfigureDNS(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CloudflareConfigureDNSRecord(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<string>;

export function CloudflareDeleteDNSRecord(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CloudflareGetDNSRecords(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CloudflarePagesAddDomain(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CloudflarePagesDeleteDomain(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CloudflarePagesGetDomains(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadFile(arg1:string):Promise<string>;

export function Exec(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GenerateProjectConfig(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateProjectConfigForSingleProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetCaptureProgress():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function List(arg1:string,arg2:string):Promise<string>;

export function ProjectDelete(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ProjectForm(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ProjectInfo(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ProjectInit(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ProjectInitWithData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ProjectPortUpdate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ProjectUpdate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ProjectUpdateWithData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveZipToDirectory(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function ServerAdd(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<string>;

export function ServerDelete(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ServerInfo(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ServerUpdate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string):Promise<string>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function TestSSHConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function TestStoredServerSSH(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestUnauthorized():Promise<string>;

export function UploadProjectConfig(arg1:string,arg2:string,arg3:string):Promise<string>;
