// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exec(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Exec'](arg1, arg2, arg3, arg4, arg5);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function List(arg1, arg2) {
  return window['go']['main']['App']['List'](arg1, arg2);
}

export function ProjectDelete(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProjectDelete'](arg1, arg2, arg3, arg4);
}

export function ProjectForm(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProjectForm'](arg1, arg2, arg3, arg4);
}

export function ProjectInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProjectInfo'](arg1, arg2, arg3);
}

export function ServerAdd(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['ServerAdd'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function ServerDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServerDelete'](arg1, arg2, arg3);
}

export function ServerInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServerInfo'](arg1, arg2, arg3);
}

export function ServerUpdate(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['ServerUpdate'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function TestSSHConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestSSHConnection'](arg1, arg2, arg3, arg4);
}

export function TestStoredServerSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestStoredServerSSH'](arg1, arg2, arg3);
}

export function TestUnauthorized() {
  return window['go']['main']['App']['TestUnauthorized']();
}
